spring.application.name=ecommercerj

# Configurações de conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Ecommerce-JERJ
spring.datasource.username=postgres
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# O segredo estratégico: 'update' faz o Hibernate criar ou atualizar as tabelas na hora que o projeto liga
spring.jpa.hibernate.ddl-auto=update

# Mostra no console do IntelliJ o comando SQL real que o Java está executando (ótimo para aprender e debugar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mostra os valores reais que substituem as interrogações (?) no console
logging.level.org.hibernate.orm.results=trace